sequenceDiagram
    EventLoop-->>EventLoop: Create

    User-->>Library: Request
    Library-->>User: (maybe) Future

    User-->>EventLoop: Register tasks and wait

    loop Until all tasks are exhausted
        EventLoop-->>Library: Execute a task

        loop Is funtion end?
            activate Library
                Library-->>EventLoop: await another future
                EventLoop-->>Library: Notify a completion
            deactivate Library
        end
    end
