sequenceDiagram
    User-->>Library: Request
    Library-->>User: Future

    User-->>EventLoop: Create
    User-->>EventLoop: Register tasks and wait

    loop For all tasks
        EventLoop-->>Library: Execute a task

        loop Is end?
            activate Library
                Library-->>EventLoop: await another future
                EventLoop-->>Library: Notify a completion
            deactivate Library
        end
    end
